# Generated by Django 3.1.7 on 2021-02-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210224_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='enabled_discord_guilds',
            new_name='discord_enabled_guilds',
        ),
        migrations.AddField(
            model_name='myuser',
            name='discord_ignored_users',
            field=models.ManyToManyField(related_name='_myuser_discord_ignored_users_+', to='users.MyUser'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='discord_tag',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='lifx_lights_list',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
