# Generated by Django 3.1.7 on 2021-02-25 07:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210225_0659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='discord_ignored_users',
        ),
        migrations.AddField(
            model_name='myuser',
            name='discord_ignored_users',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
