# Generated by Django 3.1.7 on 2021-02-23 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20210222_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='LIFXLight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.CharField(max_length=100)),
                ('uuid', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('group_name', models.CharField(blank=True, max_length=100)),
                ('json', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.myuser')),
            ],
        ),
    ]
