# Generated by Django 3.1.7 on 2021-02-23 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifxlight',
            old_name='label',
            new_name='label',
        ),
    ]
