# Generated by Django 3.1.7 on 2021-02-23 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0003_auto_20210223_0437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifxlight',
            old_name='_id',
            new_name='light_id',
        ),
    ]
