# Generated by Django 3.1.7 on 2021-02-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0004_auto_20210223_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifxlight',
            name='effect_color',
            field=models.CharField(default='#FF0000', max_length=10),
        ),
        migrations.AlterField(
            model_name='lifxlight',
            name='effect',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
